version: "3.7"
services:
  redis:
#    image: atf.intranet.bb.com.br:5001/redis
    image: redis
    hostname: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - .docker/redis/data/redis:/data
    networks:
      - internal
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "111.111.10.0/24"
